basic_driver:
  ros__parameters:
    usb_port:               /dev/ttyUSB0
    dxl_baud_rate:          1000000
    dxl_read_period:        0.010
    dxl_write_period:       0.010
    use_joint_states_topic: false
    use_moveit:             false
    dynamixel_info:         package://dynamixel_workbench_controllers/config/basic.yaml
    mobile_robot_config:
      separation_between_wheels: 0.0
      radius_of_wheel:           0.0

joint_2_0_driver:
  ros__parameters:
    usb_port:               /dev/ttyUSB0
    dxl_baud_rate:          1000000
    dxl_read_period:        0.010
    dxl_write_period:       0.010
    use_joint_states_topic: false
    use_moveit:             false
    dynamixel_info:         package://dynamixel_workbench_controllers/config/joint_2_0.yaml
    mobile_robot_config:
      separation_between_wheels: 0.0
      radius_of_wheel:           0.0

wheel_2_0_driver:
  ros__parameters:
    usb_port:               /dev/ttyUSB0
    dxl_baud_rate:          1000000
    dxl_read_period:        0.010
    dxl_write_period:       0.010
    use_joint_states_topic: false
    use_moveit:             false
    dynamixel_info:         package://dynamixel_workbench_controllers/config/wheel_2_0.yaml
    mobile_robot_config:
      separation_between_wheels: 0.150
      radius_of_wheel:           0.025
